const STORAGE_KEY='fama-donors-v2',CODE_KEY='fama-panel-code';
const seed=[];let donors=load(),session=null;
const $=id=>document.getElementById(id);
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||seed}catch{return seed}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(donors))}
function top(){return [...donors].filter(d=>d.total>0).sort((a,b)=>b.total-a.total).slice(0,10)}
function slot(rank,d){return d||{id:`slot-${rank}`,handle:'@user',name:'',avatar:'',total:0,placeholder:true}}
function fmt(n){return new Intl.NumberFormat('pt-BR').format(Number(n)||0)}
function clean(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}
function format(v){const c=clean(v);return c.length>4?c.slice(0,4)+'-'+c.slice(4):c}
function setStatus(text,kind=''){const el=$('panelStatus');if(el){el.textContent=text;el.className='connect-status '+kind}}
function manifest(){return{protocol:'liveplus-game-manifest-v1',gameId:'fama',name:'Rank da Fama',icon:'FA',version:'1.0.0',actions:[{id:'fama_points',label:'Adicionar pontos',description:'Adiciona pontos ao usuário que interagiu na live',params:[{id:'amount',label:'Pontos',type:'number',min:1,default:1}]}]}}
function render(){const actual=top(),list=Array.from({length:10},(_,i)=>slot(i+1,actual[i])),podium=$('podium'),order=[list[1],list[0],list[2]];podium.innerHTML=order.map((d,i)=>{const rank=i===1?1:i===0?2:3,cls=rank===1?'first':rank===3?'third':'second',avatar=d.avatar?`<img class="avatar" src="${d.avatar}" alt="${d.handle}">`:`<div class="avatar avatar-empty"></div>`;return `<article class="podium-user ${cls}"><div class="avatar-wrap">${avatar}<span class="rank-badge">${rank}</span></div><h2>${d.handle}</h2><p class="podium-points">${fmt(d.total)} pts</p></article>`}).join('');$('rankingList').innerHTML=list.slice(3).map((d,i)=>`<li class="rank-row ${d.placeholder?'placeholder':''}"><span class="rank-number">${i+4}</span><strong>${d.handle}</strong><span class="row-points">${fmt(d.total)} pts</span></li>`).join('')}
function registerGift({id,handle,name,avatar,amount}){const now=Date.now();handle=String(handle||'').trim();if(handle&&!handle.startsWith('@'))handle='@'+handle;let d=donors.find(x=>(id&&x.id===id)||(handle&&x.handle===handle));if(!d){d={id:id||handle,handle:handle||'@user',name:name||handle,avatar:avatar||'',total:0,lastSeen:now};donors.push(d)}d.handle=handle||d.handle;d.name=name||d.name;d.avatar=avatar||d.avatar;d.lastSeen=now;d.total+=(Number(amount)||0);save();render();return d}
function eventUser(data={}){return data.event?.user||data.payload?.event?.user||data.user||''}
function eventAvatar(data={}){return data.event?.avatar||data.payload?.event?.avatar||data.avatar||''}
function eventPoints(data={}){const p=data.params||data.action?.params||{},e=data.event||data.payload?.event||{};return Math.max(0,Number(p.amount)||Number(e.totalDiamonds)||Number(e.diamondValue)||0)}
async function onCommand(data={}){const action=String(data.action||data.command||'');if(action!=='fama_points')return;const user=eventUser(data),amount=eventPoints(data);if(user&&amount)registerGift({id:user,handle:user,avatar:eventAvatar(data),amount});session?.sendState?.({scope:'command',gameId:'fama',commandStatus:user&&amount?'executed':'ignored',action,at:Date.now()})}
async function connect(){const input=$('panelCode'),code=clean(input?.value);if(input)input.value=format(code);if(code.length!==8){setStatus('Código inválido','err');return false}if(!window.LivePlusGameSession){setStatus('SDK não carregou','err');return false}try{session?.disconnect?.()}catch{}setStatus('Conectando…','warn');session=new LivePlusGameSession({storageKey:'fama-liveplus-session',manifest:manifest()});session.addEventListener('connected',()=>{setStatus('Conectado','ok');session.sendState({scope:'initial',gameId:'fama',ranking:top()})});session.addEventListener('command',e=>onCommand(e.detail||{}));session.addEventListener('reconnecting',()=>setStatus('Reconectando…','warn'));session.addEventListener('lost',()=>setStatus('Conexão perdida','err'));session.addEventListener('rejected',e=>setStatus(e.detail?.reason||'Sessão recusada','err'));try{localStorage.setItem(CODE_KEY,format(code));await session.connect(code);return true}catch(err){setStatus(err?.message||'Falha ao conectar','err');return false}}
function openModal(){const m=$('connectModal');if(m){m.hidden=false;requestAnimationFrame(()=>$('panelCode')?.focus())}}
function closeModal(){const m=$('connectModal');if(m)m.hidden=true}
function bind(){const trigger=$('secretConnect'),input=$('panelCode');trigger?.addEventListener('click',openModal);trigger?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openModal()}});$('closeConnect')?.addEventListener('click',closeModal);document.querySelector('[data-close-connect]')?.addEventListener('click',closeModal);$('connectPanel')?.addEventListener('click',connect);if(input){try{const saved=localStorage.getItem(CODE_KEY);if(saved)input.value=format(saved)}catch{}input.addEventListener('input',e=>e.target.value=format(e.target.value));input.addEventListener('keydown',e=>{if(e.key==='Enter')connect()})}}
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});document.addEventListener('gestureend',e=>e.preventDefault(),{passive:false});
window.Fama={registerGift,markViewer({id,handle}){const d=donors.find(x=>x.id===id||x.handle===handle);if(d){d.lastSeen=Date.now();save();render();return d}return null},getTop:()=>top(),connect,resetDemo(){donors=[];save();render()}};
save();render();bind();